<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin3dsd
 * Date: Tue, 22 Apr 2014 01:38:58 -0700
 */

$conf['title'] = 'Magento Ikantam';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';

// end auto-generated content
